export enum Event {
  createClass = 'NFT.ClassCreated',
  createInstance = 'NFT.InstanceMinted',
  transfer = 'NFT.InstanceTransferred',
  burn = 'NFT.InstanceBurned',
  destroy = 'NFT.ClassDestroyed',
  priceUpdate = 'Marketplace.TokenPriceUpdated',
  sold = 'Marketplace.TokenSold',
  placeOffer = 'Marketplace.OfferPlaced',
  withdrawOffer = 'Marketplace.OfferWithdrawn',
  acceptOffer = 'Marketplace.OfferAccepted',
  payRoyalty = 'Marketplace.RoyaltyPaid',
  addRoyalty = 'Marketplace.RoyaltyAdded',
  registerAsset = 'AssetRegistry.Registered',
  updateAsset = 'AssetRegistry.Updated',
  setAssetMetadata = 'AssetRegistry.MetadataSet',
}

export enum Extrinsic {
  createClass = 'NFT.createClass',
  mint = 'NFT.mint',
  transfer = 'NFT.transfer',
  burn = 'NFT.burn',
  destroyClass = 'NFT.destroyClass',
  acceptOffer = 'Marketplace.acceptOffer',
  addRoyalty = 'Marketplace.addRoyalty',
  buy = 'Marketplace.buy',
  makeOffer = 'Marketplace.makeOffer',
  setPrice = 'Marketplace.setPrice',
  withdrawOffer = 'Marketplace.withdrawOffer',
}
